### PR TITLE
handle empty tokens from gh::gh_token, resolves #77

### LINKED ISSUE #77: Unable to download resources without GitHub token on WIndows
Hello, 

During a [recent check run by CRAN](https://win-builder.r-project.org/incoming_pretest/MAGMA.Celltyping_2.0.4_20220629_214517/Windows/00check.log) on our R package [`MAGMA.Celltyping`](https://github.com/neurogenomics/MAGMA_Celltyping), it was found that piggyback wasn't able to download assets from GitHub on Windows when a GH PAT wasn't supplied. I'm unable to supply a GH token since the checks are being run on CRAN's servers.

```
...
...
  Content type 'application/zip' length 511626945 bytes (487.9 MB)
  ==================================================
  downloaded 487.9 MB
  
  Unzipping file.
  i Downloading "NCBI37.3.gene.loc"...
  
    |                                                                            
    |                                                                      |   0%
    |                                                                            
    |======================================================================| 100%
  Saving full merged results to ==> D:\temp\Rtmp02KW2e/working_dir\Rtmp6pBFLr/MAGMA_celltyping..lvl1.csv
  Saving full merged results to ==> D:\temp\Rtmp02KW2e/working_dir\Rtmp6pBFLr/MAGMA_celltyping..lvl1.csv
  28 results @ FDR < 1
  [ FAIL 4 | WARN 12 | SKIP 0 | PASS 59 ]
  
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Error (test-calculate_conditional_geneset_enrichment.R:4:9): calculate_conditional_geneset_enrichment works ──
  Error in `load(fileName)`: bad restore file magic number (file may be corrupted) -- no data loaded
  Backtrace:
      ▆
   1. └─MAGMA.Celltyping::get_ctd("ctd_allKI") at test-calculate_conditional_geneset_enrichment.R:4:8
   2.   └─MAGMA.Celltyping:::load_rdata(tmp)
   3.     └─base::load(fileName)
  ── Error (test-drop_genes_within_mhc.r:4:5): drop_genes_within_mhc works ───────
  Error in `get_data_check(tmp = tmp)`: piggyback::pb_download() failed due to bad GitHub credentials. Please add a GitHub Personal Access Token (PAT) to your ~/.Renviron file and restart R before retrying this function.
  e.g.:
  
      GITHUB_TOKEN=<your_PAT_here> 
  
  If you do not yet have a GitHub PAT, please follow instructions here:
  
      https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
  Backtrace:
      ▆
   1. └─MAGMA.Celltyping:::get_genomeLocFile(build = "GRCH37") at test-drop_genes_within_mhc.r:4:4
   2.   └─MAGMA.Celltyping:::get_data(...)
   3.     └─MAGMA.Celltyping:::get_data_check(tmp = tmp)
  ── Error (test-get_genomeLocFile.R:7:13): get_genomeLocFile works ──────────────
  Error in `get_data_check(tmp = tmp)`: piggyback::pb_download() failed due to bad GitHub credentials. Please add a GitHub Personal Access Token (PAT) to your ~/.Renviron file and restart R before retrying this function.
  e.g.:
  
      GITHUB_TOKEN=<your_PAT_here> 
...
...
```

This is reminiscent of a previous issue (#49), but appears to be only happening on Windows currently. The error message is coming from [a check that I added ](https://github.com/neurogenomics/MAGMA_Celltyping/blob/ed689f6253372bf995bc018e9a5e7d3da96c61c8/R/get_data_check.R)when this was happening on all OS. I don't think this is showing up in your GHA checks bc I believe you're supplying your GHA PAT in as a global workflow variable.

This recently posted Issue seems to also be related: #76 

Best, 
Brian

### PR DESCRIPTION
**Pull request by tanho63**
I identified the problem in #76 and #77 as related to https://github.com/ropensci/piggyback/blob/master/R/pb_download.R#L126 - `gh::gh_token()` returns `""` if no environment variable or token is found, which creates an `add_headers(Authorization = paste("token", "")` call, causing a bad credentials/401 error.

### CODE REVIEW

File: R/pb_download.R [hunk 1]
```diff
@@ -116,14 +116,16 @@ gh_download_asset <- function(owner,
     )
   }
 
+  auth_token <- if(.token != "") httr::add_headers(paste("token",.token))
```
Comment (cboettig) [inline R/pb_download.R:119]: looks good.  Should we have a unit test that covers this case?

**Review by cboettig — APPROVED** [review]

File: R/pb_download.R (hunk 1 above)
Comment (tanho63) [reply R/pb_download.R:119]: Yep, could steal the testthat reprex I provided earlier for sure. Just had to leave my desk but I’ll add it when I get back

Comment (tanho63) [reply R/pb_download.R:119]: Hmm. You have a test for without authentication already https://github.com/ropensci/piggyback/blob/a51a97dcf85fcdbe8cc880ead1f9a8c54021412d/tests/testthat/test-without-auth.R#L77

but I think it's borked because you compare `datasets::iris[[2]]` to `iris[[2]]` without reading in the downloaded data to the iris variable first so that test can't actually fail

Comment (tanho63) [reply R/pb_download.R:119]: Have amended test to read.delim from the tmpfile, that should cover this case going forward

**Comment by tanho63** [comment]
I read in #49 that this was initially supposed to stop_for_status() and I think that is a better approach (forcing user to be aware if it failed to download)...not sure if you'd be open to switching that back and getting rid of the current `warn_for_status()` approach now that the 401 bad creds error should be resolved...

File: R/pb_download.R (hunk 1 above)
Comment (cboettig) [reply R/pb_download.R:119]: :+1: and good catch

**Comment by cboettig** [comment]
@tanho63 I'm open to more discussion as to whether we stop_for_status or warn_for_status.  The former could be more of a nuisance in large batch runs, forcing users to work around with tryCatch or equivalent, but may indeed be the most reasonable behavior by default.

**Comment by tanho63** [comment]
I had initially thought `stop_for_status()` was better, but I re-read the contents of the prev issue and apparently it still returns the correct content sometimes despite the 401 error? (This seems doubtful, I wonder if it wasn't being checked properly...) 

I think it's misleading when something gets written to the destination file that `isn't` the correct contents, but if it sometimes works I guess I don't want to break it? That said if I was writing this from scratch I'd definitely use stop instead of warn. Happy to defer to whatever you think best
